name: instapro_downloader
description: A professional Android application for downloading Instagram media.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # UI & Assets
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  fluttertoast: ^8.2.4
  percent_indicator: ^4.2.3
  
  # Networking
  dio: ^5.4.0
  dio_cookie_manager: ^3.2.0
  cookie_jar: ^4.0.0
  html: ^0.15.4
  
  # Storage & Permissions
  permission_handler: ^11.1.0
  path_provider: ^2.1.1
  path: ^1.8.3
  shared_preferences: ^2.2.2
  gallery_saver_plus: ^3.0.0 # Or any viable alternative for saving to gallery
  
  # Media & WebView
  video_player: ^2.8.2
  chewie: ^1.7.1
  webview_flutter: ^4.4.2
  url_launcher: ^6.2.2
  
  # Utils
  intl: ^0.19.0
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
